namespace ModemAPI
{
    public struct CIoCILLowLatShortResponseBody
    {
        /// <summary>
        /// true if there was one or more errors during the response parsing, otherwise - false.
        /// </summary>
        public bool IsResponseDamaged;
        /// <summary>
        /// true if the Remote Address Machine can operate and exchange on Large Messages, otherwise - false.
        /// </summary>
        public bool RemoteAddressMachineSupportsLargeMessageOperation;
        /// <summary>
        /// Does this response contain a Set Modem Local Adderss (SMLA) procedure.
        /// </summary>
        public bool ContainsSMLA;
        /// <summary>
        /// Does this response specify Maximum Transmission Unit (MTU) for packets of this Low Latency Connection.
        /// </summary>
        public bool SpecifiesPacketMTU;
        /// <summary>
        /// Does this response specify Maximum Transmission Unit (MTU) for Large Messages of this Low Latency Connection.
        /// </summary>
        public bool SpecifiesLargeMessageMTU;
        /// <summary>
        /// Does this response specify timeout for this connection in nanoseconds.
        /// </summary>
        public bool SpecifiesConnectionTimeoutInNanoseconds;
        /// <summary>
        /// If <see>ContainsSMLA</see> is true, this field must contain an Address, generated by the Remote Address Machine.
        /// </summary>
        public Address? PossibleSMLA;
        /// <summary>
        /// If <see>SpecifiesPacketMTU</see> is true, this field must contain a MTU value for packets.
        /// </summary>
        public ushort? PossiblePacketMTU;
        /// <summary>
        /// If <see>SpecifiesLargeMessageMTU</see> is true, this field must contain a MTU value for Large Messages.
        /// </summary>
        public ulong? PossibleLargeMessageMTU;
        /// <summary>
        /// If <see>SpecifiesConnectionTimeoutInNanoseconds</see> is true, this field must contain a Timeout, when the Remote Address Machine marks current Low Latency Connection inactive.
        /// </summary>
        public ulong? PossibleConnectionTimeoutInNanoseconds;
    }
}
