<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="README.md" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SocketIOClient" Version="4.0.5" />
    <PackageReference Include="System.IO.Hashing" Version="9.0.6" />
    <PackageReference Include="System.IO.Ports" Version="9.0.5" />
  </ItemGroup>

</Project>
